describe('cadastrar', () => {
  context('quando o usuário tenta se cadastrar na plataforma', () => {
    it('deve cadastrar com sucesso', () => {
      cy.visit('https://automationexercise.com')
      cy.get('[alt="Website for automation practice"]').should('be.visible')
      cy.contains('a', 'Signup / Login').click()
      cy.contains('h2', 'New User Signup!').should('be.visible')
      cy.get('[data-qa="signup-name"]').type('Fulano')
      cy.get('[data-qa="signup-email"]').type('fulano@fulano.com')
      cy.get('[data-qa="signup-button"]').click()
      cy.get('[class^=title]').should('be.visible')
      cy.get('input[id="id_gender1"]').check()
      cy.get('[data-qa="password"]').type('pwd123')
      cy.get('#days')
        .select('7')
        .invoke('val')
        .should('eq', '7')
      cy.get('[data-qa="months"]')
        .select('December')
        .invoke('val')
        .should('eq', '12')
      cy.get('[name="years"]')
        .select('1986')
        .invoke('val')
        .should('eq', '1986')
      cy.get('#newsletter')
        .click()
      cy.get('#optin')
        .click()
      cy.get('input[data-qa="first_name"]')
        .type('Fulano')
      cy.get('#last_name')
        .type('Beltrano')
      cy.get('input[data-qa="company"]')
        .type('CESAR')
      cy.get('input[data-qa="address"]')
        .type('Rua do Aprendizado')
      cy.get('input[data-qa="address2"]')
        .type('Casa do Saber')
      cy.get('[data-qa="country"]')
        .select('Australia')
        .invoke('val')
        .should('eq', 'Australia')
      cy.get('input[data-qa="state"]')
        .type('New South Wales')
      cy.get('input[data-qa="city"]')
        .type('Sydney')
      cy.get('input[data-qa="zipcode"]')
        .type('2018')
      cy.get('input[data-qa="mobile_number"]')
        .type('123456789')
      cy.get('button[data-qa="create-account"]')
        .click()
      cy.get('[data-qa="account-created"]').should('be.visible')
      cy.get('[data-qa="continue-button"]').click()
      cy.get('[class$=fa-user]').should('be.visible')
      cy.get('[class$=fa-trash-o]').click()
      cy.get('[data-qa="account-deleted"]').should('be.visible')
      cy.get('[data-qa="continue-button"]').click()
    })
  })
})