describe('cadastrar', () => {
  context('quando o usuário tenta se cadastrar na plataforma', () => {
    it('deve cadastrar com sucesso', () => {
      cy.visit('https://automationexercise.com')
      cy.get('[alt="Website for automation practice"]').should('be.visible')
      cy.contains('a', 'Signup / Login').click()
      cy.contains('h2', 'New User Signup!').should('be.visible')
      cy.get('[data-qa="signup-name"]').type('Fulano')
      cy.get('[data-qa="signup-email"]').type('fulano@fulano.com')
      cy.get('[data-qa="signup-button"]').click()
      cy.get('[class^=title]').should('be.visible')
      cy.get('[data-qa="password"]').type('pwd123')
      cy.get('#days')
        .select('7')
        .invoke('val')
        .should('eq', '7')
      cy.get('[data-qa="months"]')
        .select('December')
        .invoke('val')
        .should('eq', '12')
      cy.get('[name="years"]')
        .select('1986')
        .invoke('val')
        .should('eq', '1986')
      cy.get('#newsletter')
        .click()
      cy.get('#optin')
        .click()
      cy.get('input[data-qa="first_name"]')
        .type('Fulano')
      cy.get('#last_name')
        .type('Beltrano')
      cy.get('input[data-qa="company"]')
        .type('CESAR')
    })
  })
})